[package]
name = "neutron-sdk"
description = "Neutron CosmWasm SDK for interacting with Neutron blockchain"
version = "0.6.1"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/neutron-org/neutron-sdk"
homepage = "https://neutron.org"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
cosmwasm-std = { version = "1.3.0", features = ["staking"] }
cosmos-sdk-proto = { version = "0.16.0", default-features = false }
prost = "0.11"
serde = { version = "1.0.149", default-features = false, features = ["derive"] }
schemars = "0.8.10"
serde-json-wasm = "0.5.1"
cw-storage-plus = { version = "1.1.0", features = ["iterator"]}
base64 = "0.21.2"
bech32 = "0.9.1"
thiserror = { version = "1.0" }
serde_json = { version = "1.0.87" }
protobuf = { version = "3.2.0", features = ["with-bytes"] }
cosmwasm-schema = "1.3.0"

[dev-dependencies]
cosmwasm-schema = { version = "1.3.0", default-features = false }
prost-types = "0.11.1"
hex = "0.4.3"
