[package]
name = "cwd-voting"
version = "0.2.0"
edition = "2021"
authors = ["ekez ekez@withoutdoing.com"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "Types and methods for CosmWasm DAO voting."

[dependencies]
neutron-sdk = { package = "neutron-sdk", version = "0.6.1" }
cosmwasm-std = { version = "1.3.0" }
schemars = "0.8.8"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cw20 = "1.1.0"
cwd-interface = { path = "../cwd-interface" }
cwd-macros = { path = "../cwd-macros" }
cwd-core = { path = "../../contracts/dao/cwd-core" }
cw-denom = { path = "../cw-denom" }
cw-utils = { version = "1.0.1" }
cw-storage-plus = "1.1.0"
