[package]
name = "cwd-hooks"
version = "0.2.0"
edition = "2021"
authors = ["Adarsh"]
repository = "https://github.com/DA0-DA0/dao-contracts"
description = "A package for managing a set of hooks which can be accessed by their index."

[dependencies]
schemars = "0.8.8"
serde = { version = "1.0.175", default-features = false, features = ["derive"] }
thiserror = { version = "1.0" }
cosmwasm-std = { version = "1.3.0" }
cw-storage-plus = "1.1.0"
